version: '2'

services:
  nearme:
    image: dmytromarchenko1998/nearme-service:nearme
    depends_on:
      - 'database'
    ports: 
      - '3005:3005'
  gallery:
    image: dmytromarchenko1998/nearme-service:gallery
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
  business-info:
    image: dmytromarchenko1998/nearme-service:business-info
    depends_on:
      - 'database'
    ports: 
      - '3002:3002'
  proxy:
    build: Dmytro-Proxy/
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'

  database:
    image: mongo:latest