version: '2'

services:
  nearme:
    build: NearMe-service/ 
    depends_on:
      - 'database'
    ports: 
      - '3005:3005'
  gallery:
    image: dmytromarchenko1998/nearme-service:gallery
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
  business-info:
    build: business-info-service/ 
    depends_on:
      - 'database'
    ports: 
      - '3002:3002'
  proxy:
    image: dmytromarchenko1998/nearme-service:proxy
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'

  database:
    image: mongo:latest